### PR TITLE
Custom background gradient

### PR DESCRIPTION
**Pull request by MrOnosa**
I wanted to help address this roadmap task: https://github.com/mue/mue/projects/2#card-46048710
This PR adds a way to select multiple colours which creates a simple gradient. For now, gradients only go from top to bottom. If this PR is accepted, I planned on adding the following functionality in separate PRs: radial gradient support, better UI for sorting colors, angle of gradient control, and a way to preview the gradient.

Users that already have a background colour set will have their local storage automatically upgrade to my new standard.

### CODE REVIEW

**Comment by MrOnosa** [comment]
Also, if you do not want me to merge to the master branch until the gradient feature is 100% done, I would be happy to create a PR for a different branch.

**Comment by ohlookitsderpy** [comment]
Thank you for submitting this! All looks fine apart from a few things:

The padding now looks a little odd on the custom background colour:
(New)
image
(Old)
image

I can't drag the colour selector anymore
(New)
image
(Old)
image

Padding issue (and no text?)
image

**Review by ohlookitsderpy — CHANGES_REQUESTED** [review]
See the comment 

(git won't let me request changes with an empty comment here)

**Comment by MrOnosa** [comment]
I agree. All concerns resolved, including some from Discord.

**Review by ohlookitsderpy — APPROVED** [review]
LGTM!

**Pull request merged**
