### PR TITLE
Fix default language

### PR DESCRIPTION
**Pull request by Vicente015**
This fixes the default language not working

### CODE REVIEW

**Comment by Vicente015** [comment]
Seems to work for me :)

imagen

**Comment by davidjcralph** [comment]
LGTM

**Comment by davidjcralph** [comment]
image
Looks like the commits duplicated, oh well 😄

**Comment by Vicente015** [comment]
> image
> Looks like the commits duplicated, oh well smile

I updated the main branch of the fork with the main of this repo to see the changes with the new translations and then I merged it without squash, it's my first time doing something like that so i guess that was why, sorry xD

**Pull request merged**
