### PR TITLE
Add a bit css improvement on dropdowns

### PR DESCRIPTION
**Pull request by ssw99**

### CODE REVIEW

**Comment by alexsparkes** [comment]
I like the path of which you have taken the dropdown. it does look quite a bit cleaner and better in my opinion. However, I do think that the padding of the right arrow is a little strange, that it does not match the padding of the text. My other minor point is that the black colour on gradient may have visibility problems, however, I am unsure of this.

**Comment by ssw99** [comment]
I was going to customize the right arrow but i couldn't make css::after psudo-element to show. I will work on that tonight to see what can i do about it.

**Comment by ohlookitsderpy** [comment]
Any progress?

**Comment by ssw99** [comment]
I couldn't make it better last time i tried, then i forgot to come back. I'm going to try once more, if i can't make it better i will close the request.

**Comment by ssw99** [comment]
I'm sorry but that's the most comes out me, it's really hard to style these darn select tags.

**Comment by ssw99** [comment]
By the way, i moved dropdowns to a standalone class, but i can move it back if it's going to cause any trouble.

**Review by ohlookitsderpy — APPROVED** [review]

**Comment by ohlookitsderpy** [comment]
Thank you! Also, I think the dropdowns being in a standalone class is a good idea.

**Pull request merged**
